# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checking out gh-actions repository
        uses: actions/checkout@v3
        with:
          ref: test #branch name to which the Repo A to be merged
      
      - name: Checkout the private repo node-boilerplate
        uses: actions/checkout@v3
        with:
          repository: abhndv/node-boilerplate #Repo A Name
          ref: v0 #Repo A branch name to be merged to Repo B
          token: ${{ secrets.GH_PAT }}
          
      - name: Committing to test branch of gh-actions
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Merged changes from node-boilerplate

          # Uncomment this to commit to another branch. For new branch set `create_branch: true` also
          # branch: branchName
      
