name: CI

on:
#   push:
#     branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out local repository
        uses: actions/checkout@v3
        with:
          ref: branch-b #branch name to which the Repo A to be merged
          token: ${{ secrets.GH_PAT }}
          
#       - name: Checkout the private gh-actions-2 branch-1
#         uses: actions/checkout@v3
#         with:
#           repository: abhndv/gh-actions-2
#           ref: branch-a
#           token: ${{ secrets.GH_PAT }}
#           clean: false

      - name: Pulling from gh-actions-2 branch-a
        run: |
          git config --global user.email "<>"
          git config --global user.name "Github Actions"
          git config pull.rebase false
          git remote add master-repo https://github.com/abhndv/gh-actions-2.git
          git pull master-repo branch-a --allow-unrelated-histories
          
      - name: Pushing changes to gh-actions branch-a
        run: |
          git push
      
