name: CI

on:
#   push:
#     branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out local repository
        uses: actions/checkout@v3
        with:
          ref: test #branch name to which the Repo A to be merged

      - name: Pulling from gh-actions-2 branch-a
        run: |
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git config pull.rebase false
          git pull https://github.com/abhndv/gh-actions-2.git branch-a
          git push
          
      - name: Pushing changes 
        run: |
          git push
      
